## Spearmann rank-order correlation
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html --> spearman


(Same as Scipy spearmanr, with na_policy="omit"): https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.spearmanr.html

In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt

## Skipy can produce the p-values if needed
from scipy.stats import spearmanr, pearsonr

# Add path to project folder (official visitor stats not inlcuded in this repository..)
folder = r"PATH_TO_FOLDER"

result_folder = r"./../valid_results"

## Comparison to Kruger statistics

In [2]:
# Read in results from different origin detection approaches
fp = os.path.join(folder, "Results","results_combined_by_region_UPDATED.csv")
data = pd.read_csv(fp, sep=";")

# Read in official visitor stats
kruger = pd.read_csv(os.path.join(folder, r"Data", "OfficialVisitorStats_KNP_2014.csv"),sep=";")

In [3]:
#Check column names
data.columns.values

array(['FIPS', 'B_CircleCentroids', 'B_dbscan_500_km',
       'B_EllipseCentroids', 'B_maxdays', 'B_maxmonths', 'B_maxposts',
       'B_maxtimedelta', 'B_maxweeks', 'B_MeanCenters', 'B_MedianCenters',
       'H_CircleCentroids', 'H_dbscan_500km', 'H_EllipseCentroids',
       'H_maxdays', 'H_maxmonths', 'H_maxposts', 'H_maxtimedelta',
       'H_maxweeks', 'H_MeanCenters', 'H_MedianCenters'], dtype=object)

In [4]:
data = data.merge(kruger[["FIPS", "YEAR2014"]], left_on="FIPS", right_on="FIPS", how="inner")

In [5]:
data.head()

,FIPS,B_CircleCentroids,B_dbscan_500_km,B_EllipseCentroids,B_maxdays,B_maxmonths,B_maxposts,B_maxtimedelta,B_maxweeks,B_MeanCenters,...,H_dbscan_500km,H_EllipseCentroids,H_maxdays,H_maxmonths,H_maxposts,H_maxtimedelta,H_maxweeks,H_MeanCenters,H_MedianCenters,YEAR2014
0,AF,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,AG,37.0,NaN,37.0,NaN,NaN,NaN,NaN,NaN,37.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
3,AQ,3.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,269
4,AN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [6]:
data.to_csv("results_by_country_w_visitor_stats.csv", index=False)

Calculate spearman (all data included)

In [7]:
spearman_kruger = data.corr("spearman").sort_values(by="YEAR2014", ascending=False).YEAR2014.drop(["YEAR2014"])
spearman_kruger

H_MedianCenters       0.792670
H_maxdays             0.755382
H_maxposts            0.750377
B_dbscan_500_km       0.742077
B_maxtimedelta        0.731014
H_maxweeks            0.729573
B_maxdays             0.726139
B_maxposts            0.724705
H_dbscan_500km        0.724099
B_maxweeks            0.711962
H_maxmonths           0.711095
B_maxmonths           0.703451
B_MedianCenters       0.672511
H_maxtimedelta        0.653967
H_CircleCentroids     0.634829
H_EllipseCentroids    0.626164
H_MeanCenters         0.609696
B_MeanCenters         0.246823
B_CircleCentroids     0.240319
B_EllipseCentroids    0.235715
Name: YEAR2014, dtype: float64

In [8]:
spearman_kruger_noSF = data.set_index("FIPS").drop("SF").corr("spearman").sort_values(by="YEAR2014", ascending=False).YEAR2014.drop(["YEAR2014"])
spearman_kruger_noSF

H_MedianCenters       0.783215
H_maxdays             0.744145
H_maxposts            0.739663
B_dbscan_500_km       0.730704
B_maxtimedelta        0.717916
H_maxweeks            0.716970
B_maxdays             0.712643
H_dbscan_500km        0.712329
B_maxposts            0.711672
B_maxweeks            0.697895
H_maxmonths           0.696998
B_maxmonths           0.689035
B_MedianCenters       0.661592
H_maxtimedelta        0.638433
H_CircleCentroids     0.618741
H_EllipseCentroids    0.609477
H_MeanCenters         0.592831
B_MeanCenters         0.226723
B_CircleCentroids     0.220047
B_EllipseCentroids    0.215322
Name: YEAR2014, dtype: float64

Note, some of the visitors from "Georgia" in official stats is probably from Geogrgia, US, but we leave them in.

In [9]:
# OFFICIAL VISITORS FROM "GEORGIA"
data.loc[data["FIPS"]=="GR", "YEAR2014"]

83    512
Name: YEAR2014, dtype: int64

In [10]:
# OFFICIAL VISITORS FROM "US"
data.loc[data["FIPS"]=="US", "YEAR2014"]

229    33415
Name: YEAR2014, dtype: int64

In [11]:
# To dataframe
spearman_visitors_stats = spearman_kruger.to_frame(name="Kruger2014_all")

In [12]:
spearman_visitors_stats

                    Kruger2014_all
H_MedianCenters           0.792670
H_maxdays                 0.755382
H_maxposts                0.750377
B_dbscan_500_km           0.742077
B_maxtimedelta            0.731014
H_maxweeks                0.729573
B_maxdays                 0.726139
B_maxposts                0.724705
H_dbscan_500km            0.724099
B_maxweeks                0.711962
H_maxmonths               0.711095
B_maxmonths               0.703451
B_MedianCenters           0.672511
H_maxtimedelta            0.653967
H_CircleCentroids         0.634829
H_EllipseCentroids        0.626164
H_MeanCenters             0.609696
B_MeanCenters             0.246823
B_CircleCentroids         0.240319
B_EllipseCentroids        0.235715

In [13]:
spearman_visitors_stats.to_csv(os.path.join(folder, "Results", "spearman_kruger_visitors_statistics.csv"), sep=";")

## Scipy

If needed, can use skipy to calculate probability-values..

In [14]:
# Dummy example
spearmanr([1,2,3,4,5],[1,6,7,8,100])

SpearmanrResult(correlation=0.9999999999999999, pvalue=1.4042654220543672e-24)

In [15]:
# Apply scipy spearmanr on all columns vs. YEAR2014
scipy_spearman_kruger = data.drop(["YEAR2014", "FIPS"], axis=1).apply(lambda x: spearmanr(x, data["YEAR2014"], nan_policy="omit"), axis=0)
scipy_spearman_kruger

B_CircleCentroids      (0.24031938423013752, 0.009363580009001815)
B_dbscan_500_km        (0.7420765278349887, 8.752484058600979e-14)
B_EllipseCentroids     (0.23571489377384214, 0.010858097913833416)
B_maxdays             (0.7261387321622306, 1.1217047368792792e-11)
B_maxmonths            (0.7034511729080881, 4.498476424375208e-11)
B_maxposts             (0.7247045229431207, 4.117842229773543e-12)
B_maxtimedelta        (0.7310136681328734, 4.7200217290925065e-12)
B_maxweeks            (0.7119615273072832, 2.9482312746677316e-11)
B_MeanCenters          (0.24682316669196028, 0.007561750020639954)
B_MedianCenters       (0.6725108891925181, 1.1475322756354213e-13)
H_CircleCentroids      (0.634829180761567, 2.1161704904683832e-09)
H_dbscan_500km         (0.7240994593483061, 2.117767403509793e-13)
H_EllipseCentroids     (0.6261643411013157, 5.222564163930789e-09)
H_maxdays               (0.7553823866064904, 6.38689324429877e-14)
H_maxmonths            (0.7110952381873863, 3.193142755143029e-11)
H_maxposts            (0.7503771119268755, 1.4028768184856137e-14)
H_maxtimedelta         (0.6539670444119516, 8.327034922612565e-10)
H_maxweeks             (0.7295727619884362, 1.704722443791874e-12)
H_MeanCenters          (0.609696119248305, 1.0335560351614331e-08)
H_MedianCenters        (0.7926703113699388, 2.930244917751921e-16)
dtype: object

In [16]:
scipy_spearman = pd.DataFrame()

In [17]:
scipy_spearman["rho"]= scipy_spearman_kruger.apply(lambda x: x[0])
scipy_spearman["p"] = scipy_spearman_kruger.apply(lambda x: x[1])

In [18]:
scipy_spearman

                         rho             p
B_CircleCentroids   0.240319  9.363580e-03
B_dbscan_500_km     0.742077  8.752484e-14
B_EllipseCentroids  0.235715  1.085810e-02
B_maxdays           0.726139  1.121705e-11
B_maxmonths         0.703451  4.498476e-11
B_maxposts          0.724705  4.117842e-12
B_maxtimedelta      0.731014  4.720022e-12
B_maxweeks          0.711962  2.948231e-11
B_MeanCenters       0.246823  7.561750e-03
B_MedianCenters     0.672511  1.147532e-13
H_CircleCentroids   0.634829  2.116170e-09
H_dbscan_500km      0.724099  2.117767e-13
H_EllipseCentroids  0.626164  5.222564e-09
H_maxdays           0.755382  6.386893e-14
H_maxmonths         0.711095  3.193143e-11
H_maxposts          0.750377  1.402877e-14
H_maxtimedelta      0.653967  8.327035e-10
H_maxweeks          0.729573  1.704722e-12
H_MeanCenters       0.609696  1.033556e-08
H_MedianCenters     0.792670  2.930245e-16

In [19]:
scipy_spearman.to_csv(os.path.join(folder, "Results", "spearman_all_p_values.csv"), float_format='%.3f')

## Check top 1 country for all methods

In [20]:
data.set_index("FIPS", drop=True).idxmax()

B_CircleCentroids     SF
B_dbscan_500_km       SF
B_EllipseCentroids    SF
B_maxdays             SF
B_maxmonths           SF
B_maxposts            SF
B_maxtimedelta        SF
B_maxweeks            SF
B_MeanCenters         SF
B_MedianCenters       SF
H_CircleCentroids     SF
H_dbscan_500km        SF
H_EllipseCentroids    SF
H_maxdays             SF
H_maxmonths           SF
H_maxposts            SF
H_maxtimedelta        SF
H_maxweeks            SF
H_MeanCenters         SF
H_MedianCenters       SF
YEAR2014              SF
dtype: object

--> South Africa gets detected as the most common origin with all methods

## Spearmann correlation, version 2 (only including those users where experts agree)

In [21]:
df = pd.read_csv(os.path.join(folder, "Results", "results_combined_by_user_UPDATED.csv"), sep=";")

Group expert assesment per country

In [22]:
df["experts_OK"] = df.apply(lambda x: x["expert_1"] if x["expert_1"]==x["expert_2"] else None, axis=1)

In [23]:
df = df.drop(columns=["userid"])

Filter the data to include only those rows with expert annotations.

In [24]:
df = df.dropna(subset=['expert_1', 'expert_2'])

Get only rows where the expert annotators agree on the classification.

In [25]:
df = df.loc[df['expert_1'] == df['expert_2']]

Check number of rows

In [26]:
len(df)

375

Group by region

In [27]:
by_region = pd.DataFrame(df.apply(lambda x: x.value_counts()))
by_region

,B_CircleCentroids,B_dbscan_500_km,B_EllipseCentroids,B_maxdays,B_maxmonths,B_maxposts,B_maxtimedelta,B_maxweeks,B_MeanCenters,B_MedianCenters,...,H_maxdays,H_maxmonths,H_maxposts,H_maxtimedelta,H_maxweeks,H_MeanCenters,H_MedianCenters,expert_1,expert_2,experts_OK
AE,NaN,2.0,NaN,3.0,3.0,4.0,2.0,3.0,NaN,1.0,...,2.0,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN
AG,11.0,NaN,11.0,NaN,NaN,NaN,NaN,NaN,11.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AO,8.0,NaN,8.0,NaN,NaN,NaN,NaN,NaN,8.0,1.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
AR,NaN,1.0,NaN,1.0,1.0,1.0,1.0,1.0,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0
AS,10.0,13.0,10.0,14.0,14.0,14.0,13.0,15.0,10.0,13.0,...,14.0,13.0,13.0,12.0,13.0,10.0,13.0,13.0,13.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
UV,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
WA,13.0,NaN,13.0,NaN,NaN,NaN,NaN,NaN,13.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WZ,NaN,1.0,NaN,1.0,1.0,1.0,NaN,1.0,NaN,1.0,...,1.0,1.0,1.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0
ZA,6.0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Combine with Kruger stats

In [28]:
kruger.head()

          Country FIPS  Cntry_code  RegCode  SubregCode  YEAR2014
0     Afghanistan   AF           4      142          34         5
1         Albania   AL           8      150          39         1
2         Algeria   AG          12        2          15         8
3  American Samoa   AQ          16        9          61       269
4         Andorra   AN          20      150          39         1

In [29]:
kruger_experts = by_region.merge(kruger[["FIPS", "YEAR2014"]], left_index=True, right_on="FIPS", how="inner")
kruger_experts

,B_CircleCentroids,B_dbscan_500_km,B_EllipseCentroids,B_maxdays,B_maxmonths,B_maxposts,B_maxtimedelta,B_maxweeks,B_MeanCenters,B_MedianCenters,...,H_maxposts,H_maxtimedelta,H_maxweeks,H_MeanCenters,H_MedianCenters,expert_1,expert_2,experts_OK,FIPS,YEAR2014
217,NaN,2.0,NaN,3.0,3.0,4.0,2.0,3.0,NaN,1.0,...,2.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,AE,1190
2,11.0,NaN,11.0,NaN,NaN,NaN,NaN,NaN,11.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AG,8
5,8.0,NaN,8.0,NaN,NaN,NaN,NaN,NaN,8.0,1.0,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,AO,497
8,NaN,1.0,NaN,1.0,1.0,1.0,1.0,1.0,NaN,NaN,...,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,AR,1268
9,10.0,13.0,10.0,14.0,14.0,14.0,13.0,15.0,10.0,13.0,...,13.0,12.0,13.0,10.0,13.0,13.0,13.0,13.0,AS,13675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UV,4
197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,VM,21
144,13.0,NaN,13.0,NaN,NaN,NaN,NaN,NaN,13.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WA,603
207,NaN,1.0,NaN,1.0,1.0,1.0,NaN,1.0,NaN,1.0,...,1.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,WZ,2011
241,6.0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZA,175

In [30]:
spearman_kruger_expertsOK = kruger_experts.corr("spearman").YEAR2014.drop(["YEAR2014", "expert_1", "expert_2"]).sort_values(ascending=False)
spearman_kruger_expertsOK

experts_OK            0.809998
B_dbscan_500_km       0.789382
H_MedianCenters       0.788801
H_maxtimedelta        0.787038
B_maxposts            0.784280
B_maxweeks            0.764805
B_maxmonths           0.762879
H_maxweeks            0.760562
H_dbscan_500km        0.759051
B_maxdays             0.750885
H_maxmonths           0.743489
B_maxtimedelta        0.737783
H_maxposts            0.732103
B_MedianCenters       0.715721
H_maxdays             0.691906
H_EllipseCentroids    0.673847
H_MeanCenters         0.657967
H_CircleCentroids     0.649080
B_EllipseCentroids    0.347096
B_MeanCenters         0.347096
B_CircleCentroids     0.347096
Name: YEAR2014, dtype: float64

In [31]:
spearman_kruger_expertsOK_no_SF = kruger_experts.set_index("FIPS").drop("SF").corr("spearman").YEAR2014.drop(["YEAR2014", "expert_1", "expert_2"]).sort_values(ascending=False)
spearman_kruger_expertsOK_no_SF

experts_OK            0.791835
B_dbscan_500_km       0.771801
H_MedianCenters       0.770018
H_maxtimedelta        0.768063
B_maxposts            0.765109
B_maxweeks            0.742757
H_dbscan_500km        0.740348
B_maxmonths           0.739926
H_maxweeks            0.738665
B_maxdays             0.729083
H_maxmonths           0.720485
B_maxtimedelta        0.712363
H_maxposts            0.709871
B_MedianCenters       0.697545
H_maxdays             0.667049
H_EllipseCentroids    0.644540
H_MeanCenters         0.629536
H_CircleCentroids     0.619217
B_EllipseCentroids    0.315316
B_MeanCenters         0.315316
B_CircleCentroids     0.315316
Name: YEAR2014, dtype: float64

## Combine results

In [32]:
def detect_method_type(df, method_type="B_"):
        # Find all rows with basic/hierarchical methods
        methods = [x for x in df.index.values if x.startswith(method_type)]

        # Locate rows with basic methods
        stats = df.loc[methods]

        # Remove method identifier from index
        stats.index = [x.strip(method_type) for x in stats.index.values]
        stats.index = [x.replace("500km", "500_km") for x in stats.index.values]

        # Add method identifier to column values
        stats.columns = ["{}all".format(method_type), "{}agreedbyexperts".format(method_type)]
        

        return stats


def combine_results(df1, df2, corr_type="spearman"):
    # combine dataframes based on method name that is in index
    joined = df1.join(df2)
    
    # Separate hierarchical and basic as separate columns
    b_stats = detect_method_type(joined, "B_")
    h_stats = detect_method_type(joined, "H_")
    
    final_stats = b_stats.join(h_stats)
    
    # Organize columns
    final_stats = final_stats[['B_all', 'H_all', 'B_agreedbyexperts', 'H_agreedbyexperts']]
    
    return final_stats

### CombineSpearman results

In [33]:
final_spearman_stats = combine_results(spearman_visitors_stats, spearman_kruger_expertsOK.to_frame()).sort_values("H_all", ascending = False)
final_spearman_stats

                     B_all     H_all  B_agreedbyexperts  H_agreedbyexperts
MedianCenters     0.672511  0.792670           0.715721           0.788801
maxdays           0.726139  0.755382           0.750885           0.691906
maxposts          0.724705  0.750377           0.784280           0.732103
maxweeks          0.711962  0.729573           0.764805           0.760562
dbscan_500_km     0.742077  0.724099           0.789382           0.759051
maxmonths         0.703451  0.711095           0.762879           0.743489
maxtimedelta      0.731014  0.653967           0.737783           0.787038
CircleCentroids   0.240319  0.634829           0.347096           0.649080
EllipseCentroids  0.235715  0.626164           0.347096           0.673847
MeanCenters       0.246823  0.609696           0.347096           0.657967

In [34]:
final_spearman_stats.to_csv(os.path.join(result_folder, "spearman_stats.csv"), sep=";", float_format='%.2f')